server:
  port: 0
spring:
  application:
    name: catalog-service
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true          
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/